# Generated by Django 5.1.6 on 2025-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
