# Generated by Django 5.1.6 on 2025-03-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0007_folder_note_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
